module.exports = {
  SHIFT_START_HOUR: 9,
  SHIFT_START_MINUTE: 0,

  SHIFT_END_HOUR: 18,
  SHIFT_END_MINUTE: 0,

  LATE_AFTER_MINUTES: 15,

  HALF_DAY_HOUR: 12,
  HALF_DAY_MINUTE: 0,

  WORKING_HOURS: 8
};