const students = [
  {
    id: 1,
    admissionNo: "LSIS1001",
    rollNo: "01",
    name: "Rahul Sharma",
    fatherName: "Rakesh Sharma",
    motherName: "Sunita Sharma",
    class: "5",
    section: "A",
    gender: "Male",
    category: "General",
    house: "Blue",
    transport: "Bus",
    phone: "9876543210",
    dob: "10-02-2014",
    address: "Rajgarh, Rajasthan",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=11",
  },

  {
    id: 2,
    admissionNo: "LSIS1002",
    rollNo: "02",
    name: "Priya Singh",
    fatherName: "Mahesh Singh",
    motherName: "Anita Singh",
    class: "5",
    section: "A",
    gender: "Female",
    category: "OBC",
    house: "Green",
    transport: "Bus",
    phone: "9876543211",
    dob: "15-05-2014",
    address: "Alwar, Rajasthan",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=32",
  },

  {
    id: 3,
    admissionNo: "LSIS1003",
    rollNo: "03",
    name: "Aman Verma",
    fatherName: "Rajesh Verma",
    motherName: "Kiran Verma",
    class: "5",
    section: "A",
    gender: "Male",
    category: "SC",
    house: "Red",
    transport: "Van",
    phone: "9876543212",
    dob: "18-09-2014",
    address: "Thanagazi, Rajasthan",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=14",
  },

  {
    id: 4,
    admissionNo: "LSIS1004",
    rollNo: "04",
    name: "Sneha Kumari",
    fatherName: "Ramesh Kumar",
    motherName: "Sarla Kumari",
    class: "5",
    section: "A",
    gender: "Female",
    category: "General",
    house: "Yellow",
    transport: "Private",
    phone: "9876543213",
    dob: "20-10-2014",
    address: "Rajgarh",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=41",
  },

  {
    id: 5,
    admissionNo: "LSIS1005",
    rollNo: "05",
    name: "Mohit Yadav",
    fatherName: "Narendra Yadav",
    motherName: "Sharda Yadav",
    class: "5",
    section: "A",
    gender: "Male",
    category: "OBC",
    house: "Blue",
    transport: "Bus",
    phone: "9876543214",
    dob: "12-12-2014",
    address: "Rajgarh",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=15",
  },

  {
    id: 6,
    admissionNo: "LSIS1006",
    rollNo: "06",
    name: "Neha Gupta",
    fatherName: "Suresh Gupta",
    motherName: "Pooja Gupta",
    class: "5",
    section: "B",
    gender: "Female",
    category: "General",
    house: "Green",
    transport: "Bus",
    phone: "9876543215",
    dob: "11-01-2014",
    address: "Alwar",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=25",
  },

  {
    id: 7,
    admissionNo: "LSIS1007",
    rollNo: "07",
    name: "Rohan Meena",
    fatherName: "Ramlal Meena",
    motherName: "Kamla Meena",
    class: "5",
    section: "B",
    gender: "Male",
    category: "ST",
    house: "Red",
    transport: "Van",
    phone: "9876543216",
    dob: "22-06-2014",
    address: "Tehla",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=17",
  },

  {
    id: 8,
    admissionNo: "LSIS1008",
    rollNo: "08",
    name: "Pooja Sharma",
    fatherName: "Mukesh Sharma",
    motherName: "Seema Sharma",
    class: "5",
    section: "B",
    gender: "Female",
    category: "General",
    house: "Blue",
    transport: "Private",
    phone: "9876543217",
    dob: "08-08-2014",
    address: "Rajgarh",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=28",
  },

  {
    id: 9,
    admissionNo: "LSIS1009",
    rollNo: "09",
    name: "Vikas Sharma",
    fatherName: "Ashok Sharma",
    motherName: "Lata Sharma",
    class: "6",
    section: "A",
    gender: "Male",
    category: "General",
    house: "Yellow",
    transport: "Bus",
    phone: "9876543218",
    dob: "03-03-2013",
    address: "Alwar",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=18",
  },

  {
    id: 10,
    admissionNo: "LSIS1010",
    rollNo: "10",
    name: "Anjali Saini",
    fatherName: "Sanjay Saini",
    motherName: "Meena Saini",
    class: "6",
    section: "A",
    gender: "Female",
    category: "OBC",
    house: "Green",
    transport: "Bus",
    phone: "9876543219",
    dob: "16-07-2013",
    address: "Thanagazi",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=29",
  },

  {
    id: 11,
    admissionNo: "LSIS1011",
    rollNo: "11",
    name: "Kunal Jain",
    fatherName: "Vijay Jain",
    motherName: "Ritu Jain",
    class: "6",
    section: "A",
    gender: "Male",
    category: "General",
    house: "Blue",
    transport: "Bus",
    phone: "9876543220",
    dob: "05-04-2013",
    address: "Rajgarh",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=19",
  },

  {
    id: 12,
    admissionNo: "LSIS1012",
    rollNo: "12",
    name: "Simran Kaur",
    fatherName: "Harpreet Singh",
    motherName: "Gurpreet Kaur",
    class: "6",
    section: "B",
    gender: "Female",
    category: "General",
    house: "Red",
    transport: "Van",
    phone: "9876543221",
    dob: "13-09-2013",
    address: "Alwar",
    session: "2026-2027",
    photo: "https://i.pravatar.cc/150?img=45",
  }
];

export default students;